version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend/monitoring:/app
    restart: unless-stopped