version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend/monitoring:/app
    restart: unless-stopped
    networks:
      - hublet_net

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "5001:5000"   
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - hublet_net

  backend-devnet:
    build:
      context: ./backend_devnet
    ports:
      - "5002:5000"  # 충돌 방지
    volumes:
      - ./backend_devnet:/app
    networks:
      - hublet_net

networks:
  hublet_net:
    driver: bridge