version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend/monitoring:/app
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "5001:5000"   
    volumes:
      - ./backend:/app
    restart: unless-stopped